In [6]:

# 1.1 Create a Pandas Series named 's1_1'
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert the NumPy array into a Pandas DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

# Display the results
print("Series s1_1:")
print(s1_1)

print("\nNumPy Array np_array1_2:")
print(np_array1_2)

print("\nDataFrame df1_3:")
print(df1_3)



# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

# Your code for Task 2 here:
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

import pandas as pd
import numpy as np

# Set seed for reproducibility (optional)
np.random.seed(42)

# Create the DataFrame
df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', end='2023-04-10', periods=100),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})
# Introduce 5 random NaN values in 'Sales'
sales_nan_idx = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[sales_nan_idx, 'Sales'] = np.nan

# Introduce 3 random NaN values in 'Quantity'
qty_nan_idx = np.random.choice(df_sales.index, size=3, replace=False)
df_sales.loc[qty_nan_idx, 'Quantity'] = np.nan

# Display first few rows
print(df_sales.head())

# Verify missing values
print("\nMissing values per column:")
print(df_sales.isna().sum())
# Introduce NaN values



# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.

# Your code for Task 3 here:

print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select only the 'Region' and 'Sales' columns
df3_1 = df_sales[['Region', 'Sales']]

# 3.2 Select rows where 'Product' is 'Laptop'
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3 Select rows where 'Region' is 'East' AND 'Sales' > 500
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]

# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor'
monitor_rows = df_sales[df_sales['Product'] == 'Monitor']

# Using .loc and .iloc together
val3_4 = monitor_rows.loc[:, 'Sales'].iloc[0]

# Display results
print("df3_1:")
print(df3_1.head())

print("\ndf3_2:")
print(df3_2.head())

print("\ndf3_3:")
print(df3_3.head())

print("\nval3_4 (Sales of first Monitor entry):")
print(val3_4)

# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

# Your code for Task 4 here:

# 4.1 Check how many missing values are in each column
missing_counts4_1 = df_sales.isna().sum()

# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column
df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)

# 4.3 Drop rows that have any missing values
df4_3_dropped = df_sales.dropna()

# Display results
print("Missing values per column:")
print(missing_counts4_1)

print("\nNumber of missing values after filling Sales:")
print(df4_2_filled['Sales'].isna().sum())

print("\nOriginal shape:", df_sales.shape)
print("Shape after dropping rows with missing values:", df4_3_dropped.shape)

# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.

# Your code for Task 5 here:
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create a new column 'Total_Revenue'
# NaN values will automatically propagate
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

# 5.2 Sort by Date (ascending) and Sales (descending)
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

# 5.3 Group by Region and calculate sum of Sales and Quantity
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

# 5.4 Group by Product and calculate average Sales
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

# Display results
print("DataFrame with Total_Revenue:")
print(df_sales[['Sales', 'Quantity', 'Total_Revenue']].head())

print("\nSorted DataFrame:")
print(df5_2_sorted.head())

print("\nSum of Sales and Quantity by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

Series s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array np_array1_2:
[[ 7 68 58 75]
 [29 36 89 21]
 [36 10 73 24]]

DataFrame df1_3:
    A   B   C   D
0   7  68  58  75
1  29  36  89  21
2  36  10  73  24

--- Task 2: Synthetic Data Generation for Practice ---

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01  North  Keyboard  674.0       7.0
1 2023-01-02  South     Mouse  963.0       4.0
2 2023-01-03   East     Mouse    NaN       7.0
3 2023-01-04  North   Monitor  340.0       8.0
4 2023-01-05  North     Mouse  663.0       1.0

Missing values per column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

--- Task 3: Indexing and Slicing in DataFrames ---

--- Task 3: Indexing and Slicing in DataFrames ---
df3_1:
  Region  Sales
0  North  674.0
1  South  963.0
2   East    NaN
3  North  340.0
4  North  663.0

df3_2:
         Date Region Product  Sales  Quantity
16 202